"""users table

Revision ID: 2bfe1cf16c5e
Revises: 834b1a697901
Create Date: 2023-03-12 13:24:27.725962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bfe1cf16c5e'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mfa_token', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mfa_token')
    # ### end Alembic commands ###
