"""empty message

Revision ID: 9f875ce07420
Revises: 2bfe1cf16c5e
Create Date: 2023-03-13 14:16:44.563259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f875ce07420'
down_revision = '2bfe1cf16c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('pp')
        batch_op.drop_column('mfa_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mfa_token', sa.VARCHAR(length=16), nullable=True))
    op.add_column('user', sa.Column('pp', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
